{% set name = "pyrate-limiter" %}
{% set version = "2.8.0" %}
{% set hash_val = "1044895c9c3e37ee50a9b449e5f0d67a7995a8d456361f05c6e8afd44c8dcaec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  entry_points:
    - cover = scripts:cover
    - lint = scripts:lint
    - test = scripts:test
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6

test:
  imports:
    - pyrate_limiter
  requires:
    - pip

about:
  home: https://github.com/vutran1710/PyrateLimiter
  summary: Python rate limiter using Leaky-Bucket Algorithm Family
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/vutran1710/PyrateLimiter
  dev_url: https://github.com/vutran1710/PyrateLimiter

extra:
  recipe-maintainers:
    - jwcook
